//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OLHTX2019.Models.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class Administrator
    {
        public System.Guid Id { get; set; }
        public string Name { get; set; }
        public string LoginId { get; set; }
        public string Password { get; set; }
        public string Email { get; set; }
        public string Role { get; set; }
        public Nullable<System.DateTime> DateCreated { get; set; }
        public Nullable<System.DateTime> DateModified { get; set; }
        public Nullable<System.DateTime> DateLastLogin { get; set; }
        public Nullable<bool> IsRequiredOTP { get; set; }
        public string OtpCode { get; set; }
        public Nullable<System.DateTime> DateOtpGenerated { get; set; }
        public string Mobile { get; set; }
    }
}
