//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OLHTX2019.Models.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class AuditLog
    {
        public System.Guid Id { get; set; }
        public Nullable<System.Guid> RegId { get; set; }
        public string AdminId { get; set; }
        public string Action { get; set; }
        public string Module { get; set; }
        public string SubModule { get; set; }
        public string DataChange { get; set; }
        public Nullable<System.DateTime> DateAction { get; set; }
    }
}
